dnsmasq:
  build: ./dnsmasq
  ports:
    - "53:53/tcp"
    - "53:53/udp"
  cap_add:
    - NET_ADMIN
  volumes_from:
    - docker-hosts-watch
docker-hosts-watch:
  image: kpdecker/docker-hosts-watch
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
